events {}

http {
    # 1. Frontend Domain
    server {
        listen 80;
        server_name shoppingapp.ebrsoft.com.tr;

        location / {
            proxy_pass http://customer-app:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Admin Panel Route
        location /admin/ {
            proxy_pass http://admin-panel:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

    }

    # 2. Backend (API) Domain
    server {
        listen 80;
        server_name api.shoppingapp.ebrsoft.com.tr;

        # MinIO (File Storage) Public Access Route
        location /myshoppingapp/ {
            proxy_pass http://minio:9000/myshoppingapp/;
            proxy_set_header Host minio:9000;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            proxy_pass http://backend:8080; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Backend CLI / Swagger Erişimi (Opsiyonel olarak kapatılabilir)
        location /swagger/ {
            deny all;
        }
    }
}
