version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: shoppingdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    # Portları DIŞARI AÇMIYORUZ (Sadece docker ağı içinden erişilebilir)

  redis:
    image: redis:alpine
    restart: unless-stopped

  backend:
    build:
      context: ./MyShoppingApp
      dockerfile: src/MyShoppingApp.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=shoppingdb;Username=admin;Password=mysecretpassword
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - db
      - redis
    restart: unless-stopped
    # PORT AÇMIYORUZ! Sadece Nginx buraya erişecek.

  customer-app:
    build:
      context: ./front-end-monorepo/packages/customer-app
      dockerfile: Dockerfile
    restart: unless-stopped

  admin-panel:
    build:
      context: ./front-end-monorepo/packages/admin-panel
      dockerfile: Dockerfile
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - customer-app
      - admin-panel
      - backend
    restart: unless-stopped

volumes:
  pgdata:
